### PR TITLE
Create reclassification_vulnerabilities_gvm

### PR DESCRIPTION
**Pull request by obker**
dic to convert families given by gvm to families we want

### CODE REVIEW

**Review by nicosayer — CHANGES_REQUESTED** [review]
The file is not formatted in JSON

**Comment by nicosayer** [comment]
Also what does gvm means ?

**Comment by obker** [comment]
gvm  = one of the vulnerabilities scanner

**Comment by obker** [comment]
could you check if the format is good now por favor?

**Review by nicosayer — APPROVED** [review]

**Pull request merged**
